# Generated by Django 2.0.7 on 2018-07-31 23:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=200, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='zip')),
                ('website', models.URLField(blank=True, null=True)),
                ('agency_notes', models.TextField(blank=True, null=True, verbose_name='Notes about agency')),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(blank=True, max_length=50, null=True)),
                ('fips', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(blank=True, max_length=50, null=True)),
                ('fips', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'counties',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('chapter', models.SmallIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentation',
            },
        ),
        migrations.CreateModel(
            name='HJUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('cell', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('other_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('tz', timezone_field.fields.TimeZoneField(blank=True, choices=[('America/New_York', 'America/New_York'), ('America/Detroit', 'America/Detroit'), ('America/Kentucky/Louisville', 'America/Kentucky/Louisville'), ('America/Kentucky/Monticello', 'America/Kentucky/Monticello'), ('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'), ('America/Indiana/Vincennes', 'America/Indiana/Vincennes'), ('America/Indiana/Winamac', 'America/Indiana/Winamac'), ('America/Indiana/Marengo', 'America/Indiana/Marengo'), ('America/Indiana/Petersburg', 'America/Indiana/Petersburg'), ('America/Indiana/Vevay', 'America/Indiana/Vevay'), ('America/Chicago', 'America/Chicago'), ('America/Indiana/Tell_City', 'America/Indiana/Tell_City'), ('America/Indiana/Knox', 'America/Indiana/Knox'), ('America/Menominee', 'America/Menominee'), ('America/North_Dakota/Center', 'America/North_Dakota/Center'), ('America/North_Dakota/New_Salem', 'America/North_Dakota/New_Salem'), ('America/North_Dakota/Beulah', 'America/North_Dakota/Beulah'), ('America/Denver', 'America/Denver'), ('America/Boise', 'America/Boise'), ('America/Phoenix', 'America/Phoenix'), ('America/Los_Angeles', 'America/Los_Angeles'), ('America/Anchorage', 'America/Anchorage'), ('America/Juneau', 'America/Juneau'), ('America/Sitka', 'America/Sitka'), ('America/Metlakatla', 'America/Metlakatla'), ('America/Yakutat', 'America/Yakutat'), ('America/Nome', 'America/Nome'), ('America/Adak', 'America/Adak'), ('Pacific/Honolulu', 'Pacific/Honolulu')], null=True, verbose_name='Time Zone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'jurisdictions',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('1', 'PDF'), ('2', 'csv')], max_length=10)),
                ('hj_url', models.URLField(blank=True, null=True, unique=True, verbose_name='URL')),
                ('length', models.SmallIntegerField(blank=True, help_text='Number of pages if a PDF or records if CSV', null=True)),
                ('date_released', models.DateField(blank=True, null=True, verbose_name='Date of data release')),
                ('date_collected', models.DateField(blank=True, null=True, verbose_name='Date downloaded')),
                ('year_of_data', models.SmallIntegerField(blank=True, help_text='year the data covers', null=True)),
                ('time_period_covered', models.CharField(choices=[('1', 'monthly'), ('2', 'quarterly'), ('3', 'annual')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fips', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('assoc_press', models.CharField(blank=True, max_length=25, null=True)),
                ('census_division_name', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_federal_region', models.CharField(blank=True, max_length=50, null=True)),
                ('census_region_name', models.CharField(blank=True, max_length=50, null=True)),
                ('census_region', models.CharField(blank=True, max_length=25, null=True)),
                ('circuit_court', models.CharField(blank=True, max_length=15, null=True)),
                ('census_division', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a task to record.', max_length=100, verbose_name='Task name')),
                ('history', django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='JSON containing the tasks history.', verbose_name='History')),
            ],
            options={
                'verbose_name': 'Task History',
                'verbose_name_plural': 'Task Histories',
            },
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crime.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crime.County'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency', to='crime.City'),
        ),
        migrations.AddField(
            model_name='agency',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency2', to='crime.State', verbose_name='state'),
        ),
    ]
