# Generated by Django 2.0.7 on 2018-08-01 14:59

from django.db import migrations
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='hj_url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
