# Generated by Django 2.0.7 on 2018-08-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_auto_20180801_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jurisdiction',
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(choices=[('1', 'local'), ('2', 'county'), ('3', 'state'), ('4', 'federal'), ('5', 'special')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='agency',
            name='cities',
            field=models.ManyToManyField(related_name='cities_covered', to='crime.City', verbose_name='cities in jurisdiction'),
        ),
        migrations.AddField(
            model_name='agency',
            name='counties',
            field=models.ManyToManyField(to='crime.County', verbose_name='counties covered'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ori',
            field=models.CharField(blank=True, help_text='Federal ORI ID number for the jurisdiciton', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='help_type',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('public', 'public')], default='admin', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='Source Agency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_agency', to='crime.Agency'),
        ),
    ]
