# Generated by Django 2.0.7 on 2018-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0003_auto_20180801_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hjuser',
            options={'verbose_name': 'HJ user'},
        ),
        migrations.AddField(
            model_name='city',
            name='Alternate_County_Code_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='Federal_code_03',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='GNIS',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='OGIS_MUN_CODE',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='SSN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='Treasury_Taxation_code_03',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='character',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='msa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='muni_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='nj_muncode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state_code_1968',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
