# Generated by Django 2.0.7 on 2018-08-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0004_auto_20180803_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='ori',
            new_name='ori7',
        ),
        migrations.AddField(
            model_name='agency',
            name='ori9',
            field=models.CharField(blank=True, help_text='Federal ORI ID number for the jurisdiciton', max_length=20, null=True),
        ),
    ]
