# Generated by Django 2.0.7 on 2018-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0005_auto_20180803_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='GNIS',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='msa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
