# Generated by Django 2.0.7 on 2018-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0006_auto_20180805_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='counties',
            field=models.ManyToManyField(related_name='counties_covered', to='crime.County', verbose_name='counties covered'),
        ),
        migrations.AlterField(
            model_name='release',
            name='file_type',
            field=models.CharField(blank=True, choices=[('1', 'PDF'), ('2', 'csv')], max_length=10, null=True),
        ),
    ]
