# Generated by Django 2.0.7 on 2018-08-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0007_auto_20180807_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='time_period_covered',
            new_name='frequency_type',
        ),
    ]
