# Generated by Django 2.0.7 on 2018-08-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0008_auto_20180807_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='quarter',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
