# Generated by Django 2.0.7 on 2018-08-18 20:29

from django.db import migrations, models
import django.db.models.deletion
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0009_release_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(blank=True, choices=[('1', 'csv')], max_length=10, null=True)),
                ('hj_url', url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True, unique=True, verbose_name='URL')),
                ('date_released', models.DateField(blank=True, null=True, verbose_name='Date of data release')),
                ('date_collected', models.DateField(blank=True, null=True, verbose_name='Date downloaded')),
                ('date_converted', models.DateField(blank=True, null=True, verbose_name='Date converted from PDF to CSV')),
                ('year_of_data', models.SmallIntegerField(blank=True, help_text='year the data covers', null=True)),
                ('month_of_data', models.SmallIntegerField(blank=True, help_text='If monthly, what month', null=True)),
                ('quarter', models.SmallIntegerField(blank=True, help_text='Quarter for quarterly data only', null=True)),
                ('frequency_type', models.CharField(choices=[('1', 'monthly'), ('2', 'quarterly'), ('3', 'annual')], max_length=10)),
                ('agency', models.ForeignKey(blank=True, help_text='Agency reporting crimes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_agency', to='crime.Agency')),
                ('data_source', models.ForeignKey(blank=True, help_text='The Agency that published the original data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_source_agency', to='crime.Agency')),
                ('release', models.ForeignKey(blank=True, help_text='The original PDF the data came from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release', to='crime.Release')),
            ],
            options={
                'verbose_name_plural': 'CrimeReport',
            },
        ),
    ]
