# Generated by Django 2.0.7 on 2018-08-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0011_auto_20180823_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraped',
            options={'verbose_name_plural': 'scraped'},
        ),
        migrations.AlterField(
            model_name='scrapesite',
            name='selector',
            field=models.CharField(blank=True, help_text='An XPath selector', max_length=250, null=True),
        ),
    ]
